# Generated by Django 5.2 on 2025-05-07 10:39

import activities.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Ruxsat etilgan formatlar: .pdf, .doc, .docx, .png, .jpeg, .jpg. Maksimal hajm: 30 MB.",
                        upload_to="activities/",
                        validators=[activities.models.validate_file_extension_and_size],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Talabaning akademik o‘zlashtirishi",
                "verbose_name_plural": "Talabaning akademik o‘zlashtirishi",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Ruxsat etilgan formatlar: .pdf, .doc, .docx, .png, .jpeg, .jpg. Maksimal hajm: 30 MB.",
                        upload_to="activities/",
                        validators=[activities.models.validate_file_extension_and_size],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Darslarga to‘liq va kechikmasdan kelish",
                "verbose_name_plural": "Darslarga to‘liq va kechikmasdan kelish",
            },
        ),
        migrations.CreateModel(
            name="CompetitionAchievements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Ruxsat etilgan formatlar: .pdf, .doc, .docx, .png, .jpeg, .jpg. Maksimal hajm: 30 MB.",
                        upload_to="activities/",
                        validators=[activities.models.validate_file_extension_and_size],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ko‘rik-tanlov va musobaqalardagi natijalar",
                "verbose_name_plural": "Ko‘rik-tanlov va musobaqalardagi natijalar",
            },
        ),
        migrations.CreateModel(
            name="CulturalVisits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Ruxsat etilgan formatlar: .pdf, .doc, .docx, .png, .jpeg, .jpg. Maksimal hajm: 30 MB.",
                        upload_to="activities/",
                        validators=[activities.models.validate_file_extension_and_size],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Teatr, muzey va tarixiy qadamjolarga tashriflar",
                "verbose_name_plural": "Teatr, muzey va tarixiy qadamjolarga tashriflar",
            },
        ),
        migrations.CreateModel(
            name="DisciplineAndEthics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Ruxsat etilgan formatlar: .pdf, .doc, .docx, .png, .jpeg, .jpg. Maksimal hajm: 30 MB.",
                        upload_to="activities/",
                        validators=[activities.models.validate_file_extension_and_size],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ichki tartib va odob-axloq kodeksiga rioya etish",
                "verbose_name_plural": "Ichki tartib va odob-axloq kodeksiga rioya etish",
            },
        ),
        migrations.CreateModel(
            name="EnlightenmentLessonsParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Ruxsat etilgan formatlar: .pdf, .doc, .docx, .png, .jpeg, .jpg. Maksimal hajm: 30 MB.",
                        upload_to="activities/",
                        validators=[activities.models.validate_file_extension_and_size],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ma’rifat darslaridagi faol ishtirok",
                "verbose_name_plural": "Ma’rifat darslaridagi faol ishtirok",
            },
        ),
        migrations.CreateModel(
            name="FiveInitiativesParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Ruxsat etilgan formatlar: .pdf, .doc, .docx, .png, .jpeg, .jpg. Maksimal hajm: 30 MB.",
                        upload_to="activities/",
                        validators=[activities.models.validate_file_extension_and_size],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "5 muhim tashabbus doirasidagi to‘garaklarga faol ishtirok",
                "verbose_name_plural": "5 muhim tashabbus doirasidagi to‘garaklarga faol ishtirok",
            },
        ),
        migrations.CreateModel(
            name="ReadingCulture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Ruxsat etilgan formatlar: .pdf, .doc, .docx, .png, .jpeg, .jpg. Maksimal hajm: 30 MB.",
                        upload_to="activities/",
                        validators=[activities.models.validate_file_extension_and_size],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kitobxonlik madaniyati",
                "verbose_name_plural": "Kitobxonlik madaniyati",
            },
        ),
        migrations.CreateModel(
            name="SpiritualAndEducationalActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Ruxsat etilgan formatlar: .pdf, .doc, .docx, .png, .jpeg, .jpg. Maksimal hajm: 30 MB.",
                        upload_to="activities/",
                        validators=[activities.models.validate_file_extension_and_size],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ma’naviy-ma’rifiy sohalardagi faollik",
                "verbose_name_plural": "Ma’naviy-ma’rifiy sohalardagi faollik",
            },
        ),
        migrations.CreateModel(
            name="SportsAndHealthyLifestyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Ruxsat etilgan formatlar: .pdf, .doc, .docx, .png, .jpeg, .jpg. Maksimal hajm: 30 MB.",
                        upload_to="activities/",
                        validators=[activities.models.validate_file_extension_and_size],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sport va sog‘lom turmush tarzi",
                "verbose_name_plural": "Sport va sog‘lom turmush tarzi",
            },
        ),
        migrations.CreateModel(
            name="VolunteeringAndCommunityWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Ruxsat etilgan formatlar: .pdf, .doc, .docx, .png, .jpeg, .jpg. Maksimal hajm: 30 MB.",
                        upload_to="activities/",
                        validators=[activities.models.validate_file_extension_and_size],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Volontyorlik va jamoat ishlaridagi faollik",
                "verbose_name_plural": "Volontyorlik va jamoat ishlaridagi faollik",
            },
        ),
    ]
