# Generated by Django 5.2 on 2025-05-08 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_externalauthtoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=128)),
                ("second_name", models.CharField(blank=True, max_length=128)),
                ("third_name", models.CharField(blank=True, max_length=128)),
                ("full_name", models.CharField(blank=True, max_length=256)),
                ("image", models.URLField(blank=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("passport_pin", models.CharField(blank=True, max_length=32)),
                ("passport_number", models.CharField(blank=True, max_length=32)),
                ("university", models.CharField(blank=True, max_length=256)),
                ("group_name", models.CharField(blank=True, max_length=128)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
