# Generated by Django 5.2 on 2025-05-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0004_usergpa"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="course_level",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
